name: NeoPlaceholders
author: Neoblade298
main: me.neoblade298.neoplaceholders.NeoPlaceholders
version: 1.01
api-version: 1.14
depend: [MVdWPlaceholderAPI, PlaceholderAPI]
softdepend: [NeoBossInstances, NeoProfessions, CrossTownyServer, SkillAPI, NeoResearch]